export const FETCHINGREDIENTS = 'FETCHINGREDIENTS';
export const GETINGREDIENT = 'GETINGREDIENT';
export const INGREDIENTONCHANGE = 'INGREDIENTONCHANGE';
export const CLEARINGREDIENT = 'CLEARINGREDIENT';
