export const FETCHSUPPLEMENTS = 'FETCHSUPPLEMENTS';
export const GETSUPPLEMENT = 'GETSUPPLEMENT';
export const SUPPLEMENTONCHANGE = 'SUPPLEMENTCHANGE';
export const CLEARSUPPLEMENT = 'CLEARSUPPLEMENT';
export const DELETESUPPLEMENT = 'DELETESUPPLEMENT';
